name: 'Extract image list'
description: 'Extract a list of Docker images from a source file (Kubernetes manifest)'
inputs:
  input-file:
    description: Path to input file or folder
    required: true
  add-images:
    description: Additional images to add to the result (Json array)
    default: '[]'
outputs:
  images:
    description: List of images (Json array)
    value: ${{ steps.combine.outputs.combined_images }}
runs:
  using: "composite"
  steps:
    # - name: Install jq
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y jq
    #   shell: bash

    - name: Install yq
      uses: chrisdickinson/setup-yq@v1

    - name: Extract Images from Kubernetes manifests
      id: extract
      run: |
        images=$(yq eval-all -j '.spec.containers[].image' ${{ github.workspace }}/path/to/your/manifest.yaml)
        echo "images=$(echo $images)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Combine Image list with input
      id: combine
      run: |
        combined_images=$(jq -s '.[0] + .[1]' <<< "${{ steps.extract.outputs.images }}" "${{ inputs.add-images }}")
        echo "combined_images=$(echo $combined_images)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Display Combined Images
      run: |
        echo "Images: ${{ steps.combine.outputs.combined_images }}"
      shell: bash
