name: 'Extract image list'
description: 'Extract a list of Docker images from a source file (Kubernetes manifests or Docker Compose)'
inputs:
  input-file:
    description: Path to input file or folder
    required: true
  add-java:
    description: If Java should be added - required to run Groovy script
    # FIXME rather run in Docker?
    default: 'false'
  # add-images:
  #   description: Additional images to add to the result (Json array)
  #   default: '[]'
outputs:
  images:
    description: List of images (Json array)
    # value: ${{ steps.combine.outputs.combined_images }}
    value: ${{ steps.extract.outputs.images }}
runs:
  using: "composite"
  steps:
    - name: Install Java
      if: ${{ inputs.add-java == 'true' }}
      uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Groovy
      run: |
        sudo apt-get update && sudo apt-get install -y groovy
      shell: bash

    - name: Add action folder to path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - name: Extract Images
      id: extract
      run: |
        extract.groovy ${{ inputs.input-file }} images.json

        IMAGES=$(<images.json)

        echo "images=$(echo $IMAGES)" >> $GITHUB_OUTPUT
      shell: bash

    # - name: Combine Image list with input
    #   id: combine
    #   run: |
    #     combined_images=$(jq -s '.[0] + .[1]' <<< "${{ steps.extract.outputs.images }}" "${{ inputs.add-images }}")
    #     echo "combined_images=$(echo $combined_images)" >> $GITHUB_OUTPUT
    #   shell: bash

    - name: Display output
      run: |
        echo "Images: ${{ steps.extract.outputs.images }}"
      shell: bash
