name: 'Extract image list'
description: 'Extract a list of Docker images from a source file (Kubernetes manifests or Docker Compose)'
inputs:
  input-file:
    description: Path to input file or folder
    required: true
  add-java:
    description: If Java should be added - required to run Groovy script
    # FIXME rather run in Docker?
    default: 'false'
  add-images:
    description: Additional images to add to the result (Json array)
    default: ''
outputs:
  images:
    description: List of images (Json array)
    value: ${{ steps.extract.outputs.images }}
runs:
  using: "composite"
  steps:
    - name: Install Java
      if: ${{ inputs.add-java == 'true' }}
      uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Groovy
      run: |
        sudo apt-get update && sudo apt-get install -y groovy
      shell: bash

    - name: Add action folder to path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - name: Write file with additional images
      if: ${{ inputs.add-images != '' }}
      run: |
        cat <<EOF > extract_add_images.json
        ${{ inputs.add-images }}
        EOF
      shell: bash

    - name: Extract Images
      id: extract
      run: |
        extract.groovy ${{ inputs.input-file }} images.json extract_add_images.json

        IMAGES=$(<images.json)

        echo "images=$(echo $IMAGES)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Display output
      run: |
        echo "Images: ${{ steps.extract.outputs.images }}"
      shell: bash
